### ISSUE TITLE
Add dockerfile based on ODK which installs sbt and then builds boomer from github

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-mapping-commons#2]
Example Dockerfile:

https://github.com/Knowledge-Graph-Hub/OntoML/blob/main/Dockerfile

Add also https://github.com/Knowledge-Graph-Hub/OntoML/blob/main/repo.Makefile

**Comment by glass-ships** [comment]
This, along with #3 are presumably no longer relevant since reworking the repository, no?

**Comment by matentzn** [comment]
Yep irrelevant!
