### ISSUE TITLE
Prefix for `mesh` not conform to OBO context 

### ISSUE THREAD

**Issue by anitacaron** [monarch-initiative/monarch-mapping-commons#46]
The prefix should be `mesh` instead of `MESH` for `mondo.sssom.tsv` and `mesh_chebi_biomappings.sssom.tsv`. For reference, [OBO Context at Bioregistry](https://bioregistry.io/context/obo).

SSSOM-API can't expand or compress properly when it retrieves the' mesh' mappings, resulting in None.

![Screenshot 2023-12-01 at 16 27 41](https://github.com/monarch-initiative/monarch-mapping-commons/assets/2208124/93f869f7-c229-48d3-adbd-4294fd06f9cf)

Related to #29

**Comment by matentzn** [comment]
The prefix does not have to conform to obo context if it is included in the mappings. No curie_map in there?

**Comment by anitacaron** [comment]
SSSOM-API only depends on the OBO Context.

**Comment by hrshdhgd** [comment]
I'm a little confused. The prefix `mesh` is a as expected (as per your first statement). @matentzn why am I tagged here?

**Comment by hrshdhgd** [comment]
Yes, those were added by me via #44

**Comment by anitacaron** [comment]
Yes, these new mappings are good. One more reason to update the others. I updated the issue to be more specific.

**Comment by matentzn** [comment]
I moved this discussion here for now: https://github.com/mapping-commons/sssom-api/issues/85

@anitacaron we can attack this from two sides, but it must be from both:

1. Weaken the assumption of obo context (issue above)
2. Standardising as much as possible towards it.

@glass-ships can you make sure that all curies you output in gene mappings and chebi mesh are standardised uses `curies.Converter.standardize()` using the obo_converter()?

**Comment by glass-ships** [comment]
sure, I can try.
