### ISSUE TITLE
Fix deploy pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-mapping-commons#51]
Fix deploy pipeline
https://github.com/monarch-initiative/monarch-mapping-commons/actions/runs/8030186076/job/21937295284

We need to think about how to deploy the new versions of the mappings moving forward.

@kevinschaper where are you pulling the mappings from exactly for ETL? from the Mapping Commons release?

**Comment by glass-ships** [comment]
we currently have a Jenkins job which generates the mappings and uploads them to the gcp bucket serving 
data.monarchinitiative.org/mappings

**Comment by matentzn** [comment]
Oh great, this is much better! Thank you!

Closing!
