### ISSUE TITLE
Add mapping sets required by Monarch KG

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-mapping-commons#6]
- All `biolink:PhenotypicFeature` are aligned in uPheno (we should still add the sssom files here)
- All anatomical entities are aligned in Uberon (+bridges) (we should still add the sssom files here)
- All Diseases are aligned in Mondo (we should still add the sssom files here)

- [ ] Disease Mappings
    - "Orphanet": 5078,# `biolink:Disease`?
    - "UMLS": 8353,# `biolink:Disease`?
    - "DOID": 4368,# `biolink:Disease`
    - MONDO
    - OMIM

- [ ] Gene mappings
```
"biolink:Gene": {
     "ZFIN": 38059,
     "WB": 48773,
     "RGD": 51406,
     "SGD": 15292,
     "FB": 249446,
     "MGI": 76175,
     "HGNC": 22513,
     "POMBASE": 12818,
     "Xenbase": 50259
   },
```

- [ ] Literature mappings? 
```
      "biolink:Publication": {
        "PMID": 718683,
        "SGD": 526,
        "MGI": 8085,
        "ZFIN": 26533,
        "WB": 27457,
        "RGD": 304,
        "FB": 140315
      }
```

cc @kevinschaper

**Comment by matentzn** [comment]
@kevinschaper can you add a list of all mappings we need for the Monarch KG?

- Cross species anatomy (species specific to Uberon)
- Disease (everything to Mondo)
- Gene (the stuff you did in the genemappings repo I assume covers it)

What else? Do we need cross phenotype mappings for the Monarch KG, or is everything covered by uPheno in PHENIO?

**Comment by kevinschaper** [comment]
Right now we're only doing the Mondo mapping for diseases and [monarch-gene-mapping](https://data.monarchinitiative.org/monarch-gene-mapping/latest/gene_mappings.tsv) for genes. 

I don't have a good sense of what the requirements are for anatomy or phenotype mapping, but I'm hoping that as we get the UI up and running against the new graph those kinds of things will get more visible and that'll drive changes.

**Comment by matentzn** [comment]
Ok, whenever this issue comes up (anatomy/phenotype mappings), make sure to loop me in! Thank you!

**Comment by glass-ships** [comment]
sorry, i'm a little confused what the to-do here is?

**Comment by matentzn** [comment]
You already finished it! Just close it with the words, its done!
